name: Tesla FSD Tracker Autoupdate

on:
  schedule:
    - cron: '0 2 * * *' # Läuft vollautomatisch jede Nacht um 02:00 Uhr
  workflow_dispatch: # Erlaubt den manuellen Start über den GitHub Button

# Erzwingt den modernen Node24-Standard für fehlerfreie GitHub Actions im Jahr 2026
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Code auschecken
        uses: actions/checkout@v4

      - name: Python einrichten
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Python Scraper ausführen
        run: |
          python scraper/scrape.py

      - name: Änderungen committen und in das Repo pushen
        run: |
          git config --global user.name "FSD Bot"
          git config --global user.email "bot@fsd-tracker.local"
          git add public/data.json
          # Commit wird nur erstellt, wenn der Bot tatsächlich neue Daten gefunden hat
          git diff-index --quiet HEAD || git commit -m "Bot: data.json via RSS global aktualisiert"
          git push
