name: Tesla FSD Tracker Autoupdate

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Code auschecken
        uses: actions/checkout@v4

      - name: Python einrichten
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Twikit installieren
        run: |
          pip install twikit

      - name: Python Scraper ausführen
        env:
          X_USERNAME: ${{ secrets.X_USERNAME }}
          X_EMAIL: ${{ secrets.X_EMAIL }}
          X_PASSWORD: ${{ secrets.X_PASSWORD }}
        run: |
          python scraper/scrape.py

      - name: Änderungen committen und pushen
        run: |
          git config --global user.name "FSD Bot"
          git config --global user.email "bot@fsd-tracker.local"
          git add public/data.json
          git diff-index --quiet HEAD || git commit -m "Bot: data.json via Python aktualisiert"
          git push
