name: Tesla FSD Tracker Autoupdate

on: 
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

# Hier zwingen wir GitHub dazu, alle Aktionen direkt mit Node.js 24 auszuführen
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Code auschecken
        uses: actions/checkout@v4

      - name: Python einrichten
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Python Scraper ausführen
        run: |
          python scraper/scrape.py

      - name: Änderungen committen und pushen
        run: |
          git config --global user.name "FSD Bot"
          git config --global user.email "bot@fsd-tracker.local"
          git add public/data.json
          git diff-index --quiet HEAD || git commit -m "Bot: data.json via RSS aktualisiert"
          git push
